#:schema node_modules/wrangler/config-schema.json
name = "striae"
compatibility_date = "2024-12-30"
pages_build_output_dir = "./build/client"

[placement]
mode = "smart"

[[env.production.r2_buckets]]
binding = "STRIAE_DATA"
bucket_name = "striae-data"

[env.preview]
name = "striae-dev"
compatibility_date = "2024-12-30"
pages_build_output_dir = "./build/client"

[[env.preview.r2_buckets]]
binding = "STRIAE_DATA"
bucket_name = "striae-data"